const API='/api/v1';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let donors=[],requests=[],meta={}; let map,hospitalMarker,donorMarkers=[]; let urgencyChart,statusChart;
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const bloodLabel=g=>String(g||'').replace('_POSITIVE','+').replace('_NEGATIVE','-');
const dateLabel=d=>d?new Date(d).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'Never';
const daysSince=d=>d?Math.floor((Date.now()-new Date(d).getTime())/86400000):99999;
const eligible=d=>daysSince(d.lastDonationDate)>=Number(meta.cooldownDays||90);
const urgencyBadge=u=>`<span class="urgency ${(u||'').toLowerCase()}">${u}</span>`;
const statusBadge=s=>`<span class="status ${(s||'').toLowerCase()}">${s}</span>`;
function toast(msg,error=false){$('#toastBody').textContent=msg;$('#toast i').className=error?'bi bi-exclamation-circle-fill':'bi bi-check-circle-fill';bootstrap.Toast.getOrCreateInstance($('#toast')).show()}
async function api(path,opts={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});if(r.status===204)return null;const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||'Request failed');return data}
function setupMap(){map=L.map('map',{zoomControl:false}).setView([23.2599,77.4126],12);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map)}
function clearMarkers(){if(hospitalMarker)map.removeLayer(hospitalMarker);donorMarkers.forEach(m=>map.removeLayer(m));donorMarkers=[]}
function showMap(req,matches=[]){if(!map||!req)return;clearMarkers();map.setView([req.hospitalLatitude,req.hospitalLongitude],13);hospitalMarker=L.marker([req.hospitalLatitude,req.hospitalLongitude]).addTo(map).bindPopup(`<strong>${escapeHtml(req.hospitalName)}</strong><br>${bloodLabel(req.requiredBloodGroup)} emergency request`).openPopup();matches.forEach(m=>{const d=donors.find(x=>String(x._id)===String(m.donorId));if(!d)return;const marker=L.circleMarker([d.latitude,d.longitude],{radius:8,color:'#fff',weight:2,fillColor:'#10b981',fillOpacity:.95}).addTo(map).bindPopup(`<strong>${escapeHtml(m.donorName)}</strong><br>${bloodLabel(m.bloodGroup)} · ${m.distanceInKm} km`);donorMarkers.push(marker)});}
async function loadStats(){const x=await api('/stats');$('#statDonors').textContent=x.data.donors;$('#statAvailable').textContent=x.data.availableDonors;$('#statOpen').textContent=x.data.openRequests;$('#statCritical').textContent=x.data.criticalRequests;$('#navOpenCount').textContent=x.data.openRequests}
async function loadRequests(){requests=(await api('/requests')).data;renderRequests();renderPriority();fillMatchSelect();}
async function loadDonors(){donors=(await api('/donors')).data;renderDonors();}
function renderPriority(){const active=requests.filter(r=>r.status==='OPEN').sort((a,b)=>({CRITICAL:0,HIGH:1,MEDIUM:2,LOW:3}[a.urgencyLevel]-({CRITICAL:0,HIGH:1,MEDIUM:2,LOW:3}[b.urgencyLevel])));$('#requestList').innerHTML=active.slice(0,6).map(r=>`<div class="request-item" onclick="quickMatch('${r._id}')"><div class="d-flex justify-content-between gap-2"><div><span class="blood-badge">${bloodLabel(r.requiredBloodGroup)}</span><span class="title ms-2">${escapeHtml(r.patientName)}</span></div>${urgencyBadge(r.urgencyLevel)}</div><div class="meta"><i class="bi bi-hospital"></i> ${escapeHtml(r.hospitalName)} · ${r.unitsRequired} unit(s)</div><div class="request-bottom"><span class="meta">${new Date(r.createdAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</span><button class="btn btn-sm btn-soft" onclick="event.stopPropagation();quickMatch('${r._id}')">Match</button></div></div>`).join('')||`<div class="empty-state"><i class="bi bi-check2-circle"></i><h4>Queue is clear</h4><p>No open blood requests right now.</p></div>`}
function renderRequests(){const q=($('#requestSearch')?.value||'').toLowerCase();const sf=$('#requestStatusFilter')?.value||'';const uf=$('#requestUrgencyFilter')?.value||'';const rows=requests.filter(r=>(!sf||r.status===sf)&&(!uf||r.urgencyLevel===uf)&&(!q||[r.patientName,r.hospitalName,bloodLabel(r.requiredBloodGroup),r.status].join(' ').toLowerCase().includes(q)));$('#requestsTable').innerHTML=rows.map(r=>`<tr><td><strong>${escapeHtml(r.patientName)}</strong></td><td>${escapeHtml(r.hospitalName)}</td><td><span class="blood-badge">${bloodLabel(r.requiredBloodGroup)}</span></td><td>${r.unitsRequired}</td><td>${urgencyBadge(r.urgencyLevel)}</td><td>${statusBadge(r.status)}</td><td class="text-muted">${dateLabel(r.createdAt)}</td><td class="text-end text-nowrap">${r.status==='OPEN'?`<button class="btn btn-sm btn-soft me-1" onclick="quickMatch('${r._id}')"><i class="bi bi-bullseye"></i></button><button class="btn btn-sm btn-soft me-1" onclick="changeRequest('${r._id}','fulfill')"><i class="bi bi-check-lg"></i></button><button class="btn btn-sm btn-soft" onclick="changeRequest('${r._id}','cancel')"><i class="bi bi-x-lg"></i></button>`:'—'}</td></tr>`).join('')||`<tr><td colspan="8"><div class="empty-state">No requests match your filters.</div></td></tr>`}
function renderDonors(){const q=($('#donorSearch')?.value||'').toLowerCase();const bg=$('#donorBloodFilter')?.value||'';const av=$('#donorAvailabilityFilter')?.value||'';const rows=donors.filter(d=>(!bg||d.bloodGroup===bg)&&(!av||String(d.available)===av)&&(!q||[d.name,d.email,d.phoneNumber,bloodLabel(d.bloodGroup)].join(' ').toLowerCase().includes(q)));$('#donorsTable').innerHTML=rows.map(d=>`<tr><td><div class="fw-bold">${escapeHtml(d.name)}</div><small class="text-muted">${escapeHtml(d.email)}</small></td><td><span class="blood-badge">${bloodLabel(d.bloodGroup)}</span></td><td>${escapeHtml(d.phoneNumber)}</td><td class="text-muted">${Number(d.latitude).toFixed(4)}, ${Number(d.longitude).toFixed(4)}</td><td>${dateLabel(d.lastDonationDate)}</td><td>${eligible(d)?'<span class="text-success fw-bold">Eligible</span>':'<span class="text-danger fw-bold">Cooldown</span>'}</td><td>${d.available?'<span class="text-success fw-bold">● Available</span>':'<span class="text-muted fw-bold">● Unavailable</span>'}</td><td class="text-end text-nowrap"><button class="btn btn-sm btn-soft me-1" onclick="toggleDonor('${d._id}',${!d.available})">${d.available?'Disable':'Enable'}</button><button class="btn btn-sm btn-soft" onclick="deleteDonor('${d._id}')"><i class="bi bi-trash3"></i></button></td></tr>`).join('')||`<tr><td colspan="8"><div class="empty-state">No donors match your filters.</div></td></tr>`}
function fillMatchSelect(){$('#matchRequest').innerHTML=requests.filter(r=>r.status==='OPEN').map(r=>`<option value="${r._id}">${bloodLabel(r.requiredBloodGroup)} · ${escapeHtml(r.patientName)} · ${escapeHtml(r.hospitalName)}</option>`).join('')||'<option value="">No open requests</option>'}
async function runMatch(id){if(!id)return;const req=requests.find(r=>String(r._id)===String(id));const max=Number($('#matchDistance').value||50);$('#matchResults').innerHTML='<div class="empty-state"><i class="bi bi-arrow-repeat"></i><h4>Running matching engine...</h4><p>Checking compatibility, cooldown and distance.</p></div>';try{const x=await api(`/requests/${id}/matches?maxDistanceKm=${max}`);$('#matchCount').textContent=`${x.data.length} result${x.data.length===1?'':'s'}`;$('#matchResults').innerHTML=x.data.length?x.data.map((m,i)=>`<div class="match-card"><div class="d-flex align-items-center gap-3"><div class="match-rank">${i+1}</div><div class="flex-grow-1"><div class="fw-bold">${escapeHtml(m.donorName)} <span class="blood-badge ms-1">${bloodLabel(m.bloodGroup)}</span></div><div class="small text-muted mt-1">${escapeHtml(m.phoneNumber)} · ${escapeHtml(m.email)}</div><div class="match-reason"><i class="bi bi-check-circle-fill"></i> ${m.directBloodGroupMatch?'Direct blood group match':'ABO/Rh compatible'} · eligible</div></div><div class="text-end"><div class="match-distance">${m.distanceInKm}</div><div class="small text-muted">km away</div></div></div></div>`).join(''):`<div class="empty-state"><i class="bi bi-search"></i><h4>No eligible donors found</h4><p>Try increasing the search radius or adding available donors.</p></div>`;showMap(req,x.data)}catch(e){$('#matchResults').innerHTML=`<div class="empty-state text-danger"><i class="bi bi-exclamation-circle"></i><h4>Matching failed</h4><p>${escapeHtml(e.message)}</p></div>`}}
async function quickMatch(id){location.hash='matches';activateSection('matches');$('#matchRequest').value=id;await runMatch(id)}
async function changeRequest(id,action){try{await api(`/requests/${id}/${action}`,{method:'PATCH'});toast(`Request ${action==='fulfill'?'fulfilled':'cancelled'} successfully`);await refreshAll()}catch(e){toast(e.message,true)}}
async function toggleDonor(id,available){try{await api(`/donors/${id}`,{method:'PUT',body:JSON.stringify({available})});toast('Donor availability updated');await refreshAll()}catch(e){toast(e.message,true)}}
async function deleteDonor(id){if(!confirm('Delete this donor permanently?'))return;try{await api(`/donors/${id}`,{method:'DELETE'});toast('Donor removed');await refreshAll()}catch(e){toast(e.message,true)}}
function exportCsv(rows,name){if(!rows.length){toast('Nothing to export',true);return}const keys=Object.keys(rows[0]);const csv=[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href);toast('CSV export downloaded')}
function renderAnalytics(){const urg=['CRITICAL','HIGH','MEDIUM','LOW'];const counts=urg.map(u=>requests.filter(r=>r.urgencyLevel===u).length);const statuses=['OPEN','FULFILLED','CANCELLED'];const sc= statuses.map(s=>requests.filter(r=>r.status===s).length);const opts={responsive:true,plugins:{legend:{position:'bottom',labels:{color:getComputedStyle(document.documentElement).getPropertyValue('--muted'),font:{size:10}}}},scales:{y:{beginAtZero:true,ticks:{precision:0,color:getComputedStyle(document.documentElement).getPropertyValue('--muted')},grid:{color:getComputedStyle(document.documentElement).getPropertyValue('--border')}},x:{ticks:{color:getComputedStyle(document.documentElement).getPropertyValue('--muted')},grid:{display:false}}}};if(urgencyChart)urgencyChart.destroy();urgencyChart=new Chart($('#urgencyChart'),{type:'bar',data:{labels:urg,datasets:[{label:'Requests',data:counts,borderRadius:8,backgroundColor:['#ef4444','#f59e0b','#3b82f6','#94a3b8']}]},options:opts});if(statusChart)statusChart.destroy();statusChart=new Chart($('#statusChart'),{type:'doughnut',data:{labels:statuses,datasets:[{data:sc,backgroundColor:['#f59e0b','#10b981','#94a3b8'],borderWidth:0}]},options:{responsive:true,cutout:'68%',plugins:opts.plugins}})}
function activateSection(name){const valid=['dashboard','requests','donors','matches','analytics'];if(!valid.includes(name))name='dashboard';$$('.app-section').forEach(s=>s.classList.toggle('d-none',s.id!==name));$$('[data-section]').forEach(a=>a.classList.toggle('active',a.dataset.section===name));const titles={dashboard:['Operations','Emergency overview'],requests:['Operations','Blood requests'],donors:['People','Donor registry'],matches:['Decision support','Matching engine'],analytics:['Insights','Operations analytics']};$('#pageKicker').textContent=titles[name][0];$('#pageTitle').textContent=titles[name][1];if(name==='dashboard')setTimeout(()=>map?.invalidateSize(),100);if(name==='analytics')renderAnalytics();$('#sidebar').classList.remove('open')}
async function refreshAll(){await Promise.all([loadStats(),loadRequests(),loadDonors()]);if(location.hash.includes('analytics'))renderAnalytics()}
function setupTheme(){const saved=localStorage.getItem('bloodconnect-theme')||'light';document.documentElement.dataset.theme=saved;$('#themeToggle').innerHTML=saved==='dark'?'<i class="bi bi-sun-fill"></i>':'<i class="bi bi-moon-stars-fill"></i>';$('#themeToggle').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('bloodconnect-theme',next);$('#themeToggle').innerHTML=next==='dark'?'<i class="bi bi-sun-fill"></i>':'<i class="bi bi-moon-stars-fill"></i>';if(location.hash==='#analytics')renderAnalytics()}}
$$('[data-section]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();location.hash=a.dataset.section;activateSection(a.dataset.section)}));window.addEventListener('hashchange',()=>activateSection(location.hash.replace('#','')||'dashboard'));
$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');
$('#healthBtn').onclick=async()=>{try{const x=await api('/health');toast(`API ${x.status} · Database ${x.database}`)}catch(e){toast('API unavailable',true)}};
$('#fitMapBtn').onclick=()=>map?.invalidateSize();
$('#requestSearch').oninput=renderRequests;$('#requestStatusFilter').onchange=renderRequests;$('#requestUrgencyFilter').onchange=renderRequests;$('#donorSearch').oninput=renderDonors;$('#donorBloodFilter').onchange=renderDonors;$('#donorAvailabilityFilter').onchange=renderDonors;$('#refreshAnalytics').onclick=()=>renderAnalytics();
$('#runMatchBtn').onclick=()=>runMatch($('#matchRequest').value);
$('#exportRequests').onclick=()=>exportCsv(requests.map(r=>({patient:r.patientName,hospital:r.hospitalName,bloodGroup:bloodLabel(r.requiredBloodGroup),units:r.unitsRequired,urgency:r.urgencyLevel,status:r.status,created:dateLabel(r.createdAt)})),'bloodconnect-requests.csv');
$('#exportDonors').onclick=()=>exportCsv(donors.map(d=>({name:d.name,email:d.email,phone:d.phoneNumber,bloodGroup:bloodLabel(d.bloodGroup),latitude:d.latitude,longitude:d.longitude,lastDonation:dateLabel(d.lastDonationDate),eligible:eligible(d),available:d.available})),'bloodconnect-donors.csv');
$('#requestForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),body=Object.fromEntries(f.entries());body.unitsRequired=Number(body.unitsRequired);body.hospitalLatitude=Number(body.hospitalLatitude);body.hospitalLongitude=Number(body.hospitalLongitude);try{await api('/requests',{method:'POST',body:JSON.stringify(body)});bootstrap.Modal.getInstance($('#requestModal')).hide();e.target.reset();toast('Emergency request created');await refreshAll()}catch(err){toast(err.message,true)}});
$('#donorForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),body=Object.fromEntries(f.entries());body.latitude=Number(body.latitude);body.longitude=Number(body.longitude);body.available=f.has('available');if(!body.lastDonationDate)body.lastDonationDate=null;try{await api('/donors',{method:'POST',body:JSON.stringify(body)});bootstrap.Modal.getInstance($('#donorModal')).hide();e.target.reset();$('#donorForm [name=available]').checked=true;toast('Donor registered successfully');await refreshAll()}catch(err){toast(err.message,true)}});
async function init(){setupTheme();setupMap();try{meta=(await api('/meta'));const opts=meta.bloodGroups.map(g=>`<option value="${g}">${bloodLabel(g)}</option>`).join('');$$('#requestModal select[name=requiredBloodGroup],#donorModal select[name=bloodGroup]').forEach(s=>s.innerHTML=opts);$('#donorBloodFilter').insertAdjacentHTML('beforeend',opts);await refreshAll();activateSection(location.hash.replace('#','')||'dashboard')}catch(e){console.error(e);toast('Cannot connect. Start MongoDB and the Node.js server.',true)}}
init();
